AWSTemplateFormatVersion: '2010-09-09'
Description: Redis

Parameters:
  Subnet1:
    Description: The first subnet
    Type: String

  Subnet2:
    Description: The second subnet
    Type: String

  VPC:
    Description: The VPC
    Type: String

Resources:
  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0

  Redis:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      CacheSubnetGroupName: !Ref MyElasticacheSubnetGroup

# Outputs:
#   REDIS_HOST:
#     Value: Redis.RedisEndpointAddress